name: Polyfills documentation

on:
  pull_request:
    paths:
      - 'README.md'
      - '.browserslistrc'
      - '.eslintrc.json'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Check Polyfills documentation and settings sync
        run: node .github/actions-scripts/polyfills-sync.js
